// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";
import getSession from "./auth-config/getSession";
import SignIn from "./components/Sign-in";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(); // 🔐 Check session at layout level

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Theme accentColor="violet">
          {!session?.user ? (
            // 🔒 If not logged in, show only SignIn
            <div className="flex items-center justify-center min-h-screen">
              <SignIn />
            </div>
          ) : (
            // ✅ If logged in, show full layout
            <>
              <Navbar />
              <main className="p-4 mt-16">{children}</main>
            </>
          )}
        </Theme>
      </body>
    </html>
  );
}
